[colors.primary]
background = '#15130f'
foreground = '#e8e1da'
 
[colors.cursor]
text = '#e8e1da'
cursor = '#d0c5b5' 
 
[colors.vi_mode_cursor]
text = '#15130f'
cursor = '#e1c386' 
 
[colors.search.matches]
foreground = '#4d463a' 
background = '#bccd97' 
 
[colors.search.focused_match]
foreground = '#4d463a' 
background = '#e1c386' 
 
[colors.footer_bar]
foreground = '#4d463a' 
background = '#e8e1da' 
 
[colors.hints.start]
foreground = '#4d463a' 
background = '#d5c5a7' 
 
[colors.hints.end]
foreground = '#4d463a' 
background = '#d5c5a7' 
 
[colors.selection]
text = '#15130f'
background = '#e1c386'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#e1c386' 
yellow = '#725b28' 
blue = '#e1c386' 
magenta = '#bccd97' 
cyan = '#d5c5a7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 